name: Magisk Build

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest ]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Set up GitHub env
        run: echo ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT >> $GITHUB_ENV
        shell: bash

      - name: Creat config.prop
        run: |
          echo version=ci > config.prop
          echo versionCode=1 >> config.prop
          echo appVersion=ci >> config.prop
          echo appVersionCode=1 >> config.prop

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Cache NDK
        id: ndk-cache
        uses: actions/cache@v2
        with:
          path: ${{ env.ANDROID_SDK_ROOT }}/ndk/magisk
          key: ${{ runner.os }}-ndk-${{ hashFiles('build.py') }}

      - name: Set up NDK
        if: steps.ndk-cache.outputs.cache-hit != 'true'
        run: python build.py ndk

      - name: Build debug
        run: python build.py -v all

      - name: Build release
        run: python build.py -r -v all
